const jsonProducts = [
    {
        "name": "Remera Gris Polo Label",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-0459-866119-1-product.jpg",
        "price": "3300",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Verde G4 Militar",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/g4-0263-656609-1-product.jpg",
        "price": "4600",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de G4 militar bordado en el brazo izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Polo Label",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-1376-884548-1-product.jpg",
        "price": "3200",
        "description": "Remera de corte clásico con cuello en V para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca G4",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/g4-8553-378323-1-product.jpg",
        "price": "3407",
        "description": "Remera lisa confeccionada en jersey de algodón, mangas cortas y cuello V con ribb. Corte slim. Un básico infaltable que viene en una variedad de colores combinables con cualquier atuendo, perfecta para uso casual, trabajo, salida nocturna, gimnasio, playa y donde quiera que vayas.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Natural Polo Label",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-2200-341089-1-product.jpg",
        "price": "2999",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Natural"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra G4 Militar",
        "stock": "30",
        "img": "https://static.dafiti.com.ar/p/g4-0241-556609-1-product.jpg",
        "price": "3142",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de G4 militar bordado en el brazo derecho. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Polo Label",
        "stock": "25",
        "img": "https://static.dafiti.com.ar/p/polo-label-7360-708519-1-product.jpg",
        "price": "3415",
        "description": "Remera clásica infaltable con cuello redondo y acompañando el logo tipo de Polo Label en el pecho izquierdo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Rosa Mistal Marble",
        "stock": "40",
        "img": "https://static.dafiti.com.ar/p/mistral-6284-2998121-1-product.jpg",
        "price": "3184",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mistral",
        "size": ["S", "M", "L"],
        "colour": ["Rosado"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Marrón Polo Label",
        "stock": "40",
        "img": "https://static.dafiti.com.ar/p/polo-label-3330-474548-1-product.jpg",
        "price": "5399",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Marrón"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Wrangler",
        "stock": "79",
        "img": "https://static.dafiti.com.ar/p/wrangler-0079-5579121-1-product.jpg",
        "price": "4059",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Wintertex",
        "stock": "90",
        "img": "https://static.dafiti.com.ar/p/wintertex-0833-460715-1-product.jpg",
        "price": "2368",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Lee Logo Fluo",
        "stock": "50",
        "img": "https://static.dafiti.com.ar/p/lee-8123-1979121-1-product.jpg",
        "price": "6369",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Lee",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Wrangler Estampada",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wrangler-7959-9318121-1-product.jpg",
        "price": "3600",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Turquesa Farenheite Whatever",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/farenheite-7107-7320221-1-product.jpg",
        "price": "3710",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Farenheite",
        "size": ["S", "M", "L"],
        "colour": ["Turquesa"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Wintertex",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wintertex-1118-360715-1-product.jpg",
        "price": "5500",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Verde Wintertex",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/wintertex-0811-099479-1-product.jpg",
        "price": "4900",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul G4 Long Fit",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/g4-1283-453409-1-product.jpg",
        "price": "18000",
        "description": "Porque la moda ya no tiene género, remera unisex de mangas cortas, fácil de usar, combina estilo y comfort. Confeccionada en 100% algodón suave, calce long fit y holgado. Si se desea un look más oversize sugerimos pedir un talle más.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Polo Label City",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-0061-111079-1-product.jpg",
        "price": "3000",
        "description": "Fiel al estilo legendario sport cool, la marca es una gran jugadora cuando se trata de moda de hombre. Los diseños clásicos y orientados a la comodidad reflejan un estilo de vida simple pero elegante. Esta remera de corte clásico, confeccionada en algodón premium, cuello redondo, estampa en pecho será un ítem clave en tu vestuario de verano.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Levis Mission Tee",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/levis-3527-982639-1-product.jpg",
        "price": "14000",
        "description": "Nuestras remeras y nuestros jeans fueron hechos la una para el otra. Hechas de suave tejido de punto Jersey, esta remera tiene un fit slim y está elaborada 100% de algodón.",
        "categories": "Remera",
        "brand": "Levis",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Wrangler",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/wrangler-8539-2418121-1-product.jpg",
        "price": "12000",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Wrangler",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/wrangler-7878-2155121-1-product.jpg",
        "price": "12000",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Polo Label Signature",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-7024-282649-1-product.jpg",
        "price": "5169",
        "description": "Remera de corte clásico, confeccionadas en 100% algodón premium, con cuello redondo para hombre, mangas corta. Luce estampa icónica en pecho. Una propuesta fiel al estilo legendario sport cool de la marca, cómoda para estar en casa, pero ideal para salidas más formales.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Wrangler Estampa",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wrangler-1456-0745121-1-product.jpg",
        "price": "8912 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Stone Singapur",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/stone-0141-610079-1-product.jpg",
        "price": "4350 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Stone",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Polo Label Logo",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/polo-label-5434-672649-1-product.jpg",
        "price": "4350 ",
        "description": "Remera de corte clásico, confeccionadas en 100% algodón premium, con cuello redondo para hombre, mangas corta. Luce estampa logo player en pecho. Una propuesta fiel al estilo legendario sport cool de la marca, cómoda para estar en casa, pero ideal para salidas más formales.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Brooksfield Siena",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/brooksfield-1389-8208121-1-product.jpg",
        "price": "4350 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Brooksfield",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Visón Braavosi Racing",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/braavosi-2303-451099-1-product.jpg",
        "price": "12534 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Braavosi",
        "size": ["S", "M", "L"],
        "colour": ["Visón"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Chelsea Market Paris",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/chelsea-market-9143-882679-1-product.jpg",
        "price": "4290  ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Chelsea Market",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Roja Wrangler Básica",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wrangler-7869-7155121-1-product.jpg",
        "price": "3833",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Bordó Polo Label",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/polo-label-2055-454934-1-product.jpg",
        "price": "3833",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Bordó"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Airborn Minimal",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/airborn-1989-190369-1-product.jpg",
        "price": "3920",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Airborn",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Airborn Rayada",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/airborn-2289-771299-1-product.jpg",
        "price": "3313",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Airborn",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Beige Stone Adonis",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/stone-8389-430079-1-product.jpg",
        "price": "8500",
        "description": "Jersey estampa con corrosión.",
        "categories": "Remera",
        "brand": "Stone",
        "size": ["S", "M", "L"],
        "colour": ["Beige"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca G4 Las Vegas",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/g4-9503-744519-1-product.jpg",
        "price": "15000",
        "description": "La remera se ha convertido en la prenda imprescindible del verano. Es básica, sencilla y no requiere de mucho pensamiento para combinarla. Es un recurso que siempre debemos tener, pero cuando se trata de marcar la diferencia un buen diseño es imprescindible. Aunque todo es más fácil si conoces la marca adecuada para no ir vestido igual que el resto. Esta remera de G4 confeccionada en jersey 100% algodón, cuello tejido y con estampa central, es el ítem que amarás usar esta temporada.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Wintertex",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/wintertex-1150-362509-1-product.jpg",
        "price": "5200",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Stone Pekin",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/stone-2031-410079-1-product.jpg",
        "price": "4200",
        "description": "Jersey estampada con puff.",
        "categories": "Remera",
        "brand": "Stone",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Roja Mistral Logo 3D",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/mistral-7926-6926121-1-product.jpg",
        "price": "5000",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mistral",
        "size": ["S", "M", "L"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Reef Heratige Tee",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/reef-8162-2673411-1-product.jpg",
        "price": "4380",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Reef",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Bordó Mr. Town Flores",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/mr-town-3231-449069-1-product.jpg",
        "price": "5300",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mr. Town",
        "size": ["S", "M", "L"],
        "colour": ["Bordó"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Polo Label Stripes IV",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/polo-label-7508-011079-1-product.jpg",
        "price": "4200",
        "description": "Ideal para cualquier ocasión, esta remera rayada está confeccionada con jersey de algodón, cuello a contratono y logo bordado, el calce relajado es ideal para el uso diario, ya sea que vayas a salir o a quedarte en casa, lo podrás hacer con el estilo icónico de Polo Label.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Braavosi Dangerous",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/braavosi-5701-5816121-1-product.jpg",
        "price": "5000",
        "description": "Remera manga corta de algodón premium sublimada y con cuello redondo.",
        "categories": "Remera",
        "brand": "Braavosi",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Vinson Granby",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/vinson-4610-359394-1-product.jpg",
        "price": "4550",
        "description": "Remera Gris Vinson Granby",
        "categories": "Remera",
        "brand": "Vinson",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Brooksfield Print",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/brooksfield-2651-5308121-1-product.jpg",
        "price": "400",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Brooksfield",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Roja Taverniti Fortaleza",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/taverniti-6995-914248-1-product.jpg",
        "price": "650",
        "description": "Remera básica de jersey de algodón. Calce regular, manga corta y escote redondo con cuello en tejido elastizado. Un pequeño logotipo bordado en el pecho agrega el sello de calidad Taverniti a este clásico de la marca.",
        "categories": "Remera",
        "brand": "Taverniti",
        "size": ["S", "M", "L"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Braavosi Dark Future",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/braavosi-3908-4326121-1-product.jpg",
        "price": "884",
        "description": "Remera manga corta de algodón premium sublimada y con cuello redondo.",
        "categories": "Remera",
        "brand": "Braavosi",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Beige Rever Pass Con Boton",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/rever-pass-6382-159969-1-product.jpg",
        "price": "2400",
        "description": "Con botones al tono y bolsillo.",
        "categories": "Remera",
        "brand": "Rever Pass",
        "size": ["S", "M", "L"],
        "colour": ["Beige"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Celeste Mistral Malibu",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/mistral-9297-058979-1-product.jpg",
        "price": "2400",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mistral",
        "size": ["S", "M", "L"],
        "colour": ["Celeste"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Celeste Taverniti Otis",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/taverniti-1883-808839-1-product.jpg",
        "price": "2890",
        "description": "Remera de moda de algodón y poliéster con textura irregular suave al tacto, calce slim fit, manga corta y escote redondo. Lleva una estampa en el frente.",
        "categories": "Remera",
        "brand": "Taverniti",
        "size": ["S", "M", "L"],
        "colour": ["Celeste"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Celeste Reef Heritage Tee",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/reef-9067-1673411-1-product.jpg",
        "price": "21558",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Reef",
        "size": ["S", "M", "L"],
        "colour": ["Celeste"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Verde Rever Pass Al Corte",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/rever-pass-6584-036809-1-product.jpg",
        "price": "21558",
        "description": "Remera lisa con bolsillo. Terminaciones en escote y bolsillo al corte. Algodón 100%.",
        "categories": "Remera",
        "brand": "Rever Pass",
        "size": ["S", "M", "L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Violeta Levis",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/levis-1749-730399-1-product.jpg",
        "price": "29940",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Levis",
        "size": ["S", "M", "L"],
        "colour": ["Violeta"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Violeta Levis Graphic Set In Neck Circ",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/levis-1374-067579-1-product.jpg",
        "price": "9773",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Levis",
        "size": ["S", "M", "L"],
        "colour": ["Violeta"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Gris Vindon Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-0576-8019121-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Jean Azul Vinson Mosa",
        "stock": "33",
        "img": "https://static.dafiti.com.ar/p/vinson-9667-4379121-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Negro Trooper BASIC",
        "stock": "55",
        "img": "https://static.dafiti.com.ar/p/trooper-2520-582649-1-catalog-new.jpg",
        "price": "4769",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza. Confeccionado en rústico premium, con cintura elástica y puños en el ruedo.",
        "categories": "Pantalon",
        "brand": "Trooper",
        "size": ["L", "M", "S"],
        "colour": ["Negro"],
        "fabric": ["Algodón", "Polyester"],
    },
    {
        "name": "Pantalon Negro Equus Chino Praga",
        "stock": "28",
        "img": "https://static.dafiti.com.ar/p/equus-0034-967365-1-catalog-new.jpg",
        "price": "9592",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["M"],
        "colour": ["Negro"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Gris Vinson Berlin",
        "stock": "18",
        "img": "https://static.dafiti.com.ar/p/vinson-0627-756413-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Vinson Sole",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-2037-789099-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "S"],
        "colour": ["Negro"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Azul Equus Chino Praga",
        "stock": "33",
        "img": "https://static.dafiti.com.ar/p/equus-0038-167365-1-catalog-new.jpg",
        "price": "9592",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["S", "M"],
        "colour": ["Azul"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Trooper Gris Basic",
        "stock": "31",
        "img": "https://static.dafiti.com.ar/p/trooper-3257-482649-1-catalog-new.jpg",
        "price": "4769",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza. Confeccionado en rústico premium, con cintura elástica y puños en el ruedo.",
        "categories": "Pantalon",
        "brand": "Trooper",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Algodón", "Polyester"],
    },
    {
        "name": "Pantalon Azul Vinson Berlin",
        "stock": "22",
        "img": "https://static.dafiti.com.ar/p/vinson-3050-656413-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro El Genovés Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6019-856025-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L", "S"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige Lacoste Regular",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/lacoste-5870-181129-1-catalog-new.jpg",
        "price": "12239",
        "description": "Pantalón de algodón elástico con 5 bolsillos y corte entallado para hombre. Ajustado. Gabardina de algodón elásticoMarca de cocodrilo bordada en el bolsillo trasero. Marca de cocodrilo bordada en el bolsillo trasero",
        "categories": "Pantalon",
        "brand": "Lacoste",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Tommy Hilfiger Turquesa",
        "stock": "30",
        "img": "https://static.dafiti.com.ar/p/tommy-hilfiger-2530-563508-1-catalog-new.jpg",
        "price": "9610",
        "description": "Pantalón de gabardina de 5 bolsillos elastizado, hecho con algodón orgánico, con el logo de TOMMY HILFIGER bordado sobre el bolsillo trasero.",
        "categories": "Pantalon",
        "brand": "Tommy Hilfiger",
        "size": ["L", "S"],
        "colour": ["Turquesa"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Vindon Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-9945-7019121-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Vindon Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-9040-6019121-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige Vinson Berlin",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-2733-518029-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Verde Chelsea Market",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/chelsea-market-2646-617298-1-catalog-new.jpg",
        "price": "5799",
        "description": "Jogging - babucha LARRY achupinado de estilo casual confeccionado en bengalina con tiro bajo y cordón regulable a la altura de la cintura. Nuestro modelo Larry es perfecto para ocasiones urbanas y outdoors esta temporada si buscas un look casual y trendy!",
        "categories": "Pantalon",
        "brand": "Chelsea Market",
        "size": ["L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Mistral Eldridge Regular",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/mistral-1186-7898121-1-catalog-new.jpg",
        "price": "14800",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Mistral",
        "size": ["S", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Vinson Mon",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-2668-589099-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "S"],
        "colour": ["Azul"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Verde Equus Chino Praga",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-8485-613045-1-catalog-new.jpg",
        "price": "9592",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["S", "M"],
        "colour": ["Verde"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Marron Equus Chino Huez",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-8822-451519-1-catalog-new.jpg",
        "price": "13592",
        "description": "Pantalón chino sin pinzas. Tela gabardina elastizada esmerilada, de tacto suave. Moldería slim fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Marrón"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Gris Equus Oslo",
        "stock": "28",
        "img": "https://static.dafiti.com.ar/p/equus-4848-023045-1-catalog-new.jpg",
        "price": "13592",
        "description": "Pantalón tipo jean Slim fit. Tela gabardina 98%algodón 2%spandex. Con dos bolsillos delanteros laterales, bolsillo relojero y dos bolsillos traseros aplicados",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Azul Penguin 5 Pkt Denim Skinny",
        "stock": "33",
        "img": "https://static.dafiti.com.ar/p/penguin-7847-031039-1-catalog-new.jpg",
        "price": "21500",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Penguin",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Gris Equus Aint Trop",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-6449-821465-1-catalog-new.jpg",
        "price": "12392",
        "description": "Pantalón jogger chino. Tela poliéster/viscosa/spandex liso. De calce cómodo. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal en la espalda . Cintura elastizada con cordón de ajuste al tono y terminales metálicas.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "S"],
        "colour": ["Gris"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon De Vestir Chino Camel Shaffe Co",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/shaffe-co-8007-535316-1-catalog-new.jpg",
        "price": "9900",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Shaffe Co",
        "size": ["L", "M"],
        "colour": ["Camel"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige El Genovés Jogger",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6668-963957-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Verde El Genovés",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-5992-956025-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L", "M"],
        "colour": ["Verde"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Bordó Equus Chino Huez",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-4704-538139-1-catalog-new.jpg",
        "price": "13592",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Bordo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro Shaffe Co",
        "stock": "38",
        "img": "",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Shaffe Co",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Mostaza Equus Chino Munich",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-9682-491026-1-catalog-new.jpg",
        "price": "12972",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 98% algodón y 2% spandex. Moldería slim fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "S"],
        "colour": ["Mostaza"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro El Genovés",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6671-375316-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["S", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Azul El Genovés Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-3516-556025-1-catalog-new.jpg",
        "price": "10980",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Gris El Genovés Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6670-175316-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés Chino",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Rojo Equus Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-0099-308365-1-catalog-new.jpg",
        "price": "6392",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Rojo"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Beige El Genovés",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-5548-167117-1-catalog-new.jpg",
        "price": "10980",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés ",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Azul Equus Oahu",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Pantalón de calce relajado. Composicion: 51% algodón - 49% lino. Calce relaxed fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con boton en la espalda. Cremallera delantera con cierre y botón. Cintura con cordón de ajuste.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro Chelsea Market",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Chelsea Market",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Marron Vinson Berlin",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Marrón"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Gris Wrangler Rustico",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Wrangler",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Vinson Klana",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["S"],
        "colour": ["Azul"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Beige Vinson Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige Equus Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Bordó Prototype",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Prototype",
        "size": ["L", "M"],
        "colour": ["Bordo"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Wintertex Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Wintertex",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Beige Wintertex",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Wintertex",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Negro Vinson Berlin",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Harvey & Willys",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Este pantalón ofrece la combinación perfecta de un jogger urbano y un pantalón de traje clásico. Construido con una tela ultra suave en un corte recto. Las costuras en la mitad de las piernas proporcionan estructura. Como detalle lleva elástico en cintura para mayor confort.",
        "categories": "Pantalon",
        "brand": "Harvey & Willys",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Harvey & Willys",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Harvey & Willys",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro Harvey & Willys",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/harvey-willys-1103-981579-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Harvey & Willys",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Verde Vinson Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-8476-540965-1-catalog-new.jpg",
        "price": "9610",
        "description": "",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Rojo Vinson Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/mancini-9966-184278-1-product.jpg",
        "price": "9610",
        "description": "",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
]

module.exports = jsonProducts;