const jsonProducts = [
    {
        "name": "Remera Gris Polo Label",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-0459-866119-1-product.jpg",
        "price": "3300",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Verde G4 Militar",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/g4-0263-656609-1-product.jpg",
        "price": "4600",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de G4 militar bordado en el brazo izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Polo Label",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-1376-884548-1-product.jpg",
        "price": "3200",
        "description": "Remera de corte clásico con cuello en V para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca G4",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/g4-8553-378323-1-product.jpg",
        "price": "3407",
        "description": "Remera lisa confeccionada en jersey de algodón, mangas cortas y cuello V con ribb. Corte slim. Un básico infaltable que viene en una variedad de colores combinables con cualquier atuendo, perfecta para uso casual, trabajo, salida nocturna, gimnasio, playa y donde quiera que vayas.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Natural Polo Label",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-2200-341089-1-product.jpg",
        "price": "2999",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Natural"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra G4 Militar",
        "stock": "30",
        "img": "https://static.dafiti.com.ar/p/g4-0241-556609-1-product.jpg",
        "price": "3142",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de G4 militar bordado en el brazo derecho. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Polo Label",
        "stock": "25",
        "img": "https://static.dafiti.com.ar/p/polo-label-7360-708519-1-product.jpg",
        "price": "3415",
        "description": "Remera clásica infaltable con cuello redondo y acompañando el logo tipo de Polo Label en el pecho izquierdo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Rosa Mistal Marble",
        "stock": "40",
        "img": "https://static.dafiti.com.ar/p/mistral-6284-2998121-1-product.jpg",
        "price": "3184",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mistral",
        "size": ["S", "M", "L"],
        "colour": ["Rosado"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Marrón Polo Label",
        "stock": "40",
        "img": "https://static.dafiti.com.ar/p/polo-label-3330-474548-1-product.jpg",
        "price": "5399",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Marrón"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Wrangler",
        "stock": "79",
        "img": "https://static.dafiti.com.ar/p/wrangler-0079-5579121-1-product.jpg",
        "price": "4059",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Wintertex",
        "stock": "90",
        "img": "https://static.dafiti.com.ar/p/wintertex-0833-460715-1-product.jpg",
        "price": "2368",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Lee Logo Fluo",
        "stock": "50",
        "img": "https://static.dafiti.com.ar/p/lee-8123-1979121-1-product.jpg",
        "price": "6369",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Lee",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Wrangler Estampada",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wrangler-7959-9318121-1-product.jpg",
        "price": "3600",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Turquesa Farenheite Whatever",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/farenheite-7107-7320221-1-product.jpg",
        "price": "3710",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Farenheite",
        "size": ["S", "M", "L"],
        "colour": ["Turquesa"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Wintertex",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wintertex-1118-360715-1-product.jpg",
        "price": "5500",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Verde Wintertex",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/wintertex-0811-099479-1-product.jpg",
        "price": "4900",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul G4 Long Fit",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/g4-1283-453409-1-product.jpg",
        "price": "18000",
        "description": "Porque la moda ya no tiene género, remera unisex de mangas cortas, fácil de usar, combina estilo y comfort. Confeccionada en 100% algodón suave, calce long fit y holgado. Si se desea un look más oversize sugerimos pedir un talle más.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Polo Label City",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-0061-111079-1-product.jpg",
        "price": "3000",
        "description": "Fiel al estilo legendario sport cool, la marca es una gran jugadora cuando se trata de moda de hombre. Los diseños clásicos y orientados a la comodidad reflejan un estilo de vida simple pero elegante. Esta remera de corte clásico, confeccionada en algodón premium, cuello redondo, estampa en pecho será un ítem clave en tu vestuario de verano.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Levis Mission Tee",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/levis-3527-982639-1-product.jpg",
        "price": "14000",
        "description": "Nuestras remeras y nuestros jeans fueron hechos la una para el otra. Hechas de suave tejido de punto Jersey, esta remera tiene un fit slim y está elaborada 100% de algodón.",
        "categories": "Remera",
        "brand": "Levis",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Wrangler",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/wrangler-8539-2418121-1-product.jpg",
        "price": "12000",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Wrangler",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/wrangler-7878-2155121-1-product.jpg",
        "price": "12000",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Polo Label Signature",
        "stock": "70",
        "img": "https://static.dafiti.com.ar/p/polo-label-7024-282649-1-product.jpg",
        "price": "5169",
        "description": "Remera de corte clásico, confeccionadas en 100% algodón premium, con cuello redondo para hombre, mangas corta. Luce estampa icónica en pecho. Una propuesta fiel al estilo legendario sport cool de la marca, cómoda para estar en casa, pero ideal para salidas más formales.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Wrangler Estampa",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wrangler-1456-0745121-1-product.jpg",
        "price": "8912 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Stone Singapur",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/stone-0141-610079-1-product.jpg",
        "price": "4350 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Stone",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Polo Label Logo",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/polo-label-5434-672649-1-product.jpg",
        "price": "4350 ",
        "description": "Remera de corte clásico, confeccionadas en 100% algodón premium, con cuello redondo para hombre, mangas corta. Luce estampa logo player en pecho. Una propuesta fiel al estilo legendario sport cool de la marca, cómoda para estar en casa, pero ideal para salidas más formales.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Brooksfield Siena",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/brooksfield-1389-8208121-1-product.jpg",
        "price": "4350 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Brooksfield",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Visón Braavosi Racing",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/braavosi-2303-451099-1-product.jpg",
        "price": "12534 ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Braavosi",
        "size": ["S", "M", "L"],
        "colour": ["Visón"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Chelsea Market Paris",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/chelsea-market-9143-882679-1-product.jpg",
        "price": "4290  ",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Chelsea Market",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Roja Wrangler Básica",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/wrangler-7869-7155121-1-product.jpg",
        "price": "3833",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wrangler",
        "size": ["S", "M", "L"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Bordó Polo Label",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/polo-label-2055-454934-1-product.jpg",
        "price": "3833",
        "description": "Remera de corte clásico con cuello redondo para hombre. Manga corta. Logotipo de Polo Label bordado en el pecho izquierdo. 100% algodón. Lavable a máquina. Un clásico infaltable para cualquier look, nunca pasa de moda.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Bordó"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca Airborn Minimal",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/airborn-1989-190369-1-product.jpg",
        "price": "3920",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Airborn",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Airborn Rayada",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/airborn-2289-771299-1-product.jpg",
        "price": "3313",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Airborn",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Beige Stone Adonis",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/stone-8389-430079-1-product.jpg",
        "price": "8500",
        "description": "Jersey estampa con corrosión.",
        "categories": "Remera",
        "brand": "Stone",
        "size": ["S", "M", "L"],
        "colour": ["Beige"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Blanca G4 Las Vegas",
        "stock": "60",
        "img": "https://static.dafiti.com.ar/p/g4-9503-744519-1-product.jpg",
        "price": "15000",
        "description": "La remera se ha convertido en la prenda imprescindible del verano. Es básica, sencilla y no requiere de mucho pensamiento para combinarla. Es un recurso que siempre debemos tener, pero cuando se trata de marcar la diferencia un buen diseño es imprescindible. Aunque todo es más fácil si conoces la marca adecuada para no ir vestido igual que el resto. Esta remera de G4 confeccionada en jersey 100% algodón, cuello tejido y con estampa central, es el ítem que amarás usar esta temporada.",
        "categories": "Remera",
        "brand": "G4",
        "size": ["S", "M", "L"],
        "colour": ["Blanco"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Azul Wintertex",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/wintertex-1150-362509-1-product.jpg",
        "price": "5200",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Wintertex",
        "size": ["S", "M", "L"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Stone Pekin",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/stone-2031-410079-1-product.jpg",
        "price": "4200",
        "description": "Jersey estampada con puff.",
        "categories": "Remera",
        "brand": "Stone",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Roja Mistral Logo 3D",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/mistral-7926-6926121-1-product.jpg",
        "price": "5000",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mistral",
        "size": ["S", "M", "L"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Reef Heratige Tee",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/reef-8162-2673411-1-product.jpg",
        "price": "4380",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Reef",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Bordó Mr. Town Flores",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/mr-town-3231-449069-1-product.jpg",
        "price": "5300",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mr. Town",
        "size": ["S", "M", "L"],
        "colour": ["Bordó"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Polo Label Stripes IV",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/polo-label-7508-011079-1-product.jpg",
        "price": "4200",
        "description": "Ideal para cualquier ocasión, esta remera rayada está confeccionada con jersey de algodón, cuello a contratono y logo bordado, el calce relajado es ideal para el uso diario, ya sea que vayas a salir o a quedarte en casa, lo podrás hacer con el estilo icónico de Polo Label.",
        "categories": "Remera",
        "brand": "Polo Label",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Braavosi Dangerous",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/braavosi-5701-5816121-1-product.jpg",
        "price": "5000",
        "description": "Remera manga corta de algodón premium sublimada y con cuello redondo.",
        "categories": "Remera",
        "brand": "Braavosi",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Vinson Granby",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/vinson-4610-359394-1-product.jpg",
        "price": "4550",
        "description": "Remera Gris Vinson Granby",
        "categories": "Remera",
        "brand": "Vinson",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Negra Brooksfield Print",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/brooksfield-2651-5308121-1-product.jpg",
        "price": "400",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Brooksfield",
        "size": ["S", "M", "L"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Roja Taverniti Fortaleza",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/taverniti-6995-914248-1-product.jpg",
        "price": "650",
        "description": "Remera básica de jersey de algodón. Calce regular, manga corta y escote redondo con cuello en tejido elastizado. Un pequeño logotipo bordado en el pecho agrega el sello de calidad Taverniti a este clásico de la marca.",
        "categories": "Remera",
        "brand": "Taverniti",
        "size": ["S", "M", "L"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Gris Braavosi Dark Future",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/braavosi-3908-4326121-1-product.jpg",
        "price": "884",
        "description": "Remera manga corta de algodón premium sublimada y con cuello redondo.",
        "categories": "Remera",
        "brand": "Braavosi",
        "size": ["S", "M", "L"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Beige Rever Pass Con Boton",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/rever-pass-6382-159969-1-product.jpg",
        "price": "2400",
        "description": "Con botones al tono y bolsillo.",
        "categories": "Remera",
        "brand": "Rever Pass",
        "size": ["S", "M", "L"],
        "colour": ["Beige"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Celeste Mistral Malibu",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/mistral-9297-058979-1-product.jpg",
        "price": "2400",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Mistral",
        "size": ["S", "M", "L"],
        "colour": ["Celeste"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Celeste Taverniti Otis",
        "stock": "150",
        "img": "https://static.dafiti.com.ar/p/taverniti-1883-808839-1-product.jpg",
        "price": "2890",
        "description": "Remera de moda de algodón y poliéster con textura irregular suave al tacto, calce slim fit, manga corta y escote redondo. Lleva una estampa en el frente.",
        "categories": "Remera",
        "brand": "Taverniti",
        "size": ["S", "M", "L"],
        "colour": ["Celeste"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Celeste Reef Heritage Tee",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/reef-9067-1673411-1-product.jpg",
        "price": "21558",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Reef",
        "size": ["S", "M", "L"],
        "colour": ["Celeste"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Verde Rever Pass Al Corte",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/rever-pass-6584-036809-1-product.jpg",
        "price": "21558",
        "description": "Remera lisa con bolsillo. Terminaciones en escote y bolsillo al corte. Algodón 100%.",
        "categories": "Remera",
        "brand": "Rever Pass",
        "size": ["S", "M", "L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Violeta Levis",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/levis-1749-730399-1-product.jpg",
        "price": "29940",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Levis",
        "size": ["S", "M", "L"],
        "colour": ["Violeta"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Remera Violeta Levis Graphic Set In Neck Circ",
        "stock": "100",
        "img": "https://static.dafiti.com.ar/p/levis-1374-067579-1-product.jpg",
        "price": "9773",
        "description": "Remera clásica infaltable con cuello redondo. Ideal para todo tipo de salidas.",
        "categories": "Remera",
        "brand": "Levis",
        "size": ["S", "M", "L"],
        "colour": ["Violeta"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Gris Vindon Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-0576-8019121-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Jean Azul Vinson Mosa",
        "stock": "33",
        "img": "https://static.dafiti.com.ar/p/vinson-9667-4379121-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Negro Trooper BASIC",
        "stock": "55",
        "img": "https://static.dafiti.com.ar/p/trooper-2520-582649-1-catalog-new.jpg",
        "price": "4769",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza. Confeccionado en rústico premium, con cintura elástica y puños en el ruedo.",
        "categories": "Pantalon",
        "brand": "Trooper",
        "size": ["L", "M", "S"],
        "colour": ["Negro"],
        "fabric": ["Algodón", "Polyester"],
    },
    {
        "name": "Pantalon Negro Equus Chino Praga",
        "stock": "28",
        "img": "https://static.dafiti.com.ar/p/equus-0034-967365-1-catalog-new.jpg",
        "price": "9592",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["M"],
        "colour": ["Negro"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Gris Vinson Berlin",
        "stock": "18",
        "img": "https://static.dafiti.com.ar/p/vinson-0627-756413-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Vinson Sole",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-2037-789099-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "S"],
        "colour": ["Negro"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Azul Equus Chino Praga",
        "stock": "33",
        "img": "https://static.dafiti.com.ar/p/equus-0038-167365-1-catalog-new.jpg",
        "price": "9592",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["S", "M"],
        "colour": ["Azul"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Trooper Gris Basic",
        "stock": "31",
        "img": "https://static.dafiti.com.ar/p/trooper-3257-482649-1-catalog-new.jpg",
        "price": "4769",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza. Confeccionado en rústico premium, con cintura elástica y puños en el ruedo.",
        "categories": "Pantalon",
        "brand": "Trooper",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Algodón", "Polyester"],
    },
    {
        "name": "Pantalon Azul Vinson Berlin",
        "stock": "22",
        "img": "https://static.dafiti.com.ar/p/vinson-3050-656413-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro El Genovés Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6019-856025-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L", "S"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige Lacoste Regular",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/lacoste-5870-181129-1-catalog-new.jpg",
        "price": "12239",
        "description": "Pantalón de algodón elástico con 5 bolsillos y corte entallado para hombre. Ajustado. Gabardina de algodón elásticoMarca de cocodrilo bordada en el bolsillo trasero. Marca de cocodrilo bordada en el bolsillo trasero",
        "categories": "Pantalon",
        "brand": "Lacoste",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Tommy Hilfiger Turquesa",
        "stock": "30",
        "img": "https://static.dafiti.com.ar/p/tommy-hilfiger-2530-563508-1-catalog-new.jpg",
        "price": "9610",
        "description": "Pantalón de gabardina de 5 bolsillos elastizado, hecho con algodón orgánico, con el logo de TOMMY HILFIGER bordado sobre el bolsillo trasero.",
        "categories": "Pantalon",
        "brand": "Tommy Hilfiger",
        "size": ["L", "S"],
        "colour": ["Turquesa"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Vindon Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-9945-7019121-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Vindon Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-9040-6019121-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige Vinson Berlin",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-2733-518029-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Verde Chelsea Market",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/chelsea-market-2646-617298-1-catalog-new.jpg",
        "price": "5799",
        "description": "Jogging - babucha LARRY achupinado de estilo casual confeccionado en bengalina con tiro bajo y cordón regulable a la altura de la cintura. Nuestro modelo Larry es perfecto para ocasiones urbanas y outdoors esta temporada si buscas un look casual y trendy!",
        "categories": "Pantalon",
        "brand": "Chelsea Market",
        "size": ["L"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Mistral Eldridge Regular",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/mistral-1186-7898121-1-catalog-new.jpg",
        "price": "14800",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Mistral",
        "size": ["S", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Vinson Mon",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/vinson-2668-589099-1-catalog-new.jpg",
        "price": "9270",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "S"],
        "colour": ["Azul"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Verde Equus Chino Praga",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-8485-613045-1-catalog-new.jpg",
        "price": "9592",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["S", "M"],
        "colour": ["Verde"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Marron Equus Chino Huez",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-8822-451519-1-catalog-new.jpg",
        "price": "13592",
        "description": "Pantalón chino sin pinzas. Tela gabardina elastizada esmerilada, de tacto suave. Moldería slim fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Marrón"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Gris Equus Oslo",
        "stock": "28",
        "img": "https://static.dafiti.com.ar/p/equus-4848-023045-1-catalog-new.jpg",
        "price": "13592",
        "description": "Pantalón tipo jean Slim fit. Tela gabardina 98%algodón 2%spandex. Con dos bolsillos delanteros laterales, bolsillo relojero y dos bolsillos traseros aplicados",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Azul Penguin 5 Pkt Denim Skinny",
        "stock": "33",
        "img": "https://static.dafiti.com.ar/p/penguin-7847-031039-1-catalog-new.jpg",
        "price": "21500",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Penguin",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Gris Equus Aint Trop",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-6449-821465-1-catalog-new.jpg",
        "price": "12392",
        "description": "Pantalón jogger chino. Tela poliéster/viscosa/spandex liso. De calce cómodo. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal en la espalda . Cintura elastizada con cordón de ajuste al tono y terminales metálicas.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "S"],
        "colour": ["Gris"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon De Vestir Chino Camel Shaffe Co",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/shaffe-co-8007-535316-1-catalog-new.jpg",
        "price": "9900",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Shaffe Co",
        "size": ["L", "M"],
        "colour": ["Camel"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige El Genovés Jogger",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6668-963957-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Verde El Genovés",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-5992-956025-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L", "M"],
        "colour": ["Verde"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Bordó Equus Chino Huez",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-4704-538139-1-catalog-new.jpg",
        "price": "13592",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Bordo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro Shaffe Co",
        "stock": "38",
        "img": "",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Shaffe Co",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Mostaza Equus Chino Munich",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-9682-491026-1-catalog-new.jpg",
        "price": "12972",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 98% algodón y 2% spandex. Moldería slim fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "S"],
        "colour": ["Mostaza"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro El Genovés",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6671-375316-1-catalog-new.jpg",
        "price": "10890",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["S", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Azul El Genovés Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-3516-556025-1-catalog-new.jpg",
        "price": "10980",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Gris El Genovés Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-6670-175316-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés Chino",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Rojo Equus Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-0099-308365-1-catalog-new.jpg",
        "price": "6392",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Rojo"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Beige El Genovés",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/el-genoves-5548-167117-1-catalog-new.jpg",
        "price": "10980",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "El Genovés ",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Azul Equus Oahu",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Pantalón de calce relajado. Composicion: 51% algodón - 49% lino. Calce relaxed fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con boton en la espalda. Cremallera delantera con cierre y botón. Cintura con cordón de ajuste.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro Chelsea Market",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Chelsea Market",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Marron Vinson Berlin",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Marrón"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Gris Wrangler Rustico",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Wrangler",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Vinson Klana",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["S"],
        "colour": ["Azul"],
        "fabric": ["Jean"],
    },
    {
        "name": "Pantalon Beige Vinson Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Beige Equus Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Pantalón chino sin pinzas. Tela gabardina esmerilada 100% algodón. Moldería classic fit. Con dos bolsillos delanteros laterales y dos bolsillos tipo ojal con botón en la espalda. Cremallera delantera con cierre y botón.",
        "categories": "Pantalon",
        "brand": "Equus",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Bordó Prototype",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Prototype",
        "size": ["L", "M"],
        "colour": ["Bordo"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Wintertex Chino",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Wintertex",
        "size": ["L", "M"],
        "colour": ["Gris"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Beige Wintertex",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Wintertex",
        "size": ["L", "M"],
        "colour": ["Beige"],
        "fabric": ["Polyester"],
    },
    {
        "name": "Pantalon Negro Vinson Berlin",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Gabardina"],
    },
    {
        "name": "Pantalon Negro Harvey & Willys",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Este pantalón ofrece la combinación perfecta de un jogger urbano y un pantalón de traje clásico. Construido con una tela ultra suave en un corte recto. Las costuras en la mitad de las piernas proporcionan estructura. Como detalle lleva elástico en cintura para mayor confort.",
        "categories": "Pantalon",
        "brand": "Harvey & Willys",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Azul Harvey & Willys",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-1574-691408-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Harvey & Willys",
        "size": ["L", "M"],
        "colour": ["Azul"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Negro Harvey & Willys",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/harvey-willys-1103-981579-1-catalog-new.jpg",
        "price": "9610",
        "description": "Diseñado para el comfort diario y que te acompañe cualquier look, sea en un ámbito urbano o en plena naturaleza.",
        "categories": "Pantalon",
        "brand": "Harvey & Willys",
        "size": ["L", "M"],
        "colour": ["Negro"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Verde Vinson Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/equus-8476-540965-1-catalog-new.jpg",
        "price": "9610",
        "description": "",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Verde"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Pantalon Rojo Vinson Delo",
        "stock": "38",
        "img": "https://static.dafiti.com.ar/p/mancini-9966-184278-1-product.jpg",
        "price": "9610",
        "description": "",
        "categories": "Pantalon",
        "brand": "Vinson",
        "size": ["L", "M"],
        "colour": ["Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Canguro Entallado",
        "stock": "75",
        "img": "https://http2.mlstatic.com/D_NQ_NP_739273-MLA48109463776_112021-W.webp",
        "price": "5300",
        "description": "Canguro azul Angles",
        "categories": "Buzo",
        "brand": "Polo",
        "size": ["S","M","L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Afa Seleccion",
        "stock": "15",
        "img": "https://http2.mlstatic.com/D_NQ_NP_713650-MLA53496559330_012023-O.webp",
        "price": "3300",
        "description": "Buzo Afa Seleccion Argentina Campeon Del Mundo 3 Estrellas",
        "categories": "Buzo",
        "brand": "afa",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Canguro Capucha",
        "stock": "45",
        "img": "https://http2.mlstatic.com/D_NQ_NP_739273-MLA48109463776_112021-W.webp",
        "price": "6300",
        "description": "Canguro negra Angles",
        "categories": "Buzo",
        "brand": "Angles",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Entallado",
        "stock": "75",
        "img": "https://http2.mlstatic.com/D_NQ_NP_743845-MLA45515733687_042021-O.webp",
        "price": "5000",
        "description": "Buzos Entallados Friza Algodón.tela 100%calidad Premium",
        "categories": "Buzo",
        "brand": "Friza",
        "size": ["S","M","L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Canguro con mangas apretadasa",
        "stock": "27",
        "img": "https://http2.mlstatic.com/D_NQ_NP_951774-MLA32134905937_092019-O.webp",
        "price": "2300",
        "description": "Buzo Canguro Capucha Hombre Slim Fit Hoodie Camperas",
        "categories": "Buzo",
        "brand": "Polo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },  
    {
        "name": "Buzo Hombre Capucha Cruzada",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_601835-MLA47102416868_082021-O.webp",
        "price": "4000",
        "description": "Buzo Hombre Capucha Cruzada Invierno",
        "categories": "Buzo",
        "brand": "Polo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Nasa Estampado Rosa",
        "stock": "40",
        "img": "https://http2.mlstatic.com/D_NQ_NP_775535-MLA53209079847_012023-O.webp",
        "price": "4000",
        "description": "Buzo De Algodón / Nasa Estampado Rosa / Unisex",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro Unisex Capucha Ics Manga",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_906743-MLA52580117796_112022-O.webp",
        "price": "1200",
        "description": "Buzo Canguro Unisex Capucha Ics Manga",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Tik Tok Buzo Canguro Con Capucha Unisex",
        "stock": "22",
        "img": "https://http2.mlstatic.com/D_NQ_NP_770310-MLA51816584594_102022-O.webp",
        "price": "4300",
        "description": "Tik Tok Buzo Canguro Con Capucha Unisex / Friends",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Golden State Warriors - Basquet",
        "stock": "10",
        "img": "https://http2.mlstatic.com/D_NQ_NP_618793-MLA49402260140_032022-O.webp",
        "price": "4600",
        "description": "Buzo Golden State Warriors - Basquet - Hoodie Unisex Capucha",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Nba",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_977471-MLA51117007263_082022-O.webp",
        "price": "3000",
        "description": "Buzo Nba Algodón Frisa",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Nba bulls",
        "stock": "54",
        "img": "https://http2.mlstatic.com/D_NQ_NP_679574-MLA51118079062_082022-O.webp",
        "price": "4300",
        "description": "Buzo Nba Algodón Frisa",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Under Armour",
        "stock": "100",
        "img": "https://http2.mlstatic.com/D_NQ_NP_723609-MLA47140939760_082021-O.webp",
        "price": "4600",
        "description": "Buzo Under Armour Training Sportstyle Terry Logo Hombre Ng",
        "categories": "Buzo",
        "brand": "Armour",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro De Cristiano Ronaldo",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_700560-MLA53217472350_012023-O.webp",
        "price": "5000",
        "description": "Buzo Canguro De Cristiano Ronaldo / Cr7 / Unisex",
        "categories": "Buzo",
        "brand": "Armour",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },  
    {
        "name": "Buzo Canguro Con Capucha Pokemon Gengar",
        "stock": "15",
        "img": "https://http2.mlstatic.com/D_NQ_NP_795994-MLA52679280135_122022-O.webp",
        "price": "4600",
        "description": "Buzo Canguro Con Capucha Pokemon Gengar / Todos Los Talles",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro Los Simpson",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_802528-MLA43852283862_102020-O.webp",
        "price": "5500",
        "description": "Duff Beer / Buzo Canguro Los Simpson Homero",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro Game Over",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_709281-MLA52499360845_112022-O.webp",
        "price": "5000",
        "description": "Buzo Canguro Unisex / Game Over - Otaku - Hip Hop - Geek",
        "categories": "Buzo",
        "brand": "Geek",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Anti Social Social Club Buzo",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_681242-MLA51816654827_102022-O.webp",
        "price": "4300",
        "description": "Anti Social Social Club Buzo Canguro Con Capucha",
        "categories": "Buzo",
        "brand": "Keisuke",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Twenty One Pilots",
        "stock": "60",
        "img": "https://http2.mlstatic.com/D_NQ_NP_845644-MLA52500148559_112022-O.webp",
        "price": "4600",
        "description": "Twenty One Pilots - Buzo Canguro Unisex - Trench - Hip Hop",
        "categories": "Buzo",
        "brand": "Trench",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro O Cuello Redondo Wifi",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_627748-MLA52499756715_112022-O.webp",
        "price": "5500",
        "description": "Buzo Canguro O Cuello Redondo Wifi / Youtuber Team / Dorado",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Mad Cat El Rubius",
        "stock": "10",
        "img": "https://http2.mlstatic.com/D_NQ_NP_807122-MLA53487854964_012023-O.webp",
        "price": "8000",
        "description": "BMad Cat El Rubius - Buzo Canguro Unisex - Viral Youtuber",
        "categories": "Buzo",
        "brand": "Rubius",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Palta",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_989523-MLA50045339720_052022-O.webp",
        "price": "4300",
        "description": "ABuzo Palta Hoodie Fz Basico 2202v21m440 Hombre",
        "categories": "Buzo",
        "brand": "Hoodie",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Canguro Tortuga Fidji",
        "stock": "60",
        "img": "https://http2.mlstatic.com/D_NQ_NP_686725-MLA45992205078_052021-O.webp",
        "price": "4600",
        "description": "Canguro Tortuga Fidji Fidji Tienda Oficial",
        "categories": "Buzo",
        "brand": "Trench",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro Unisex Taylor Swift",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_697161-MLA52052868269_102022-O.webp",
        "price": "5800",
        "description": "Buzo Canguro Unisex - Taylor Swift Midnights 001",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Satoru Gojo",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_787258-MLA51341042054_082022-O.webp",
        "price": "4300",
        "description": "Buzo Satoru Gojo - Unisex - Anime Jujutsu Kaisen Otaku",
        "categories": "Buzo",
        "brand": "Jujutsu",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro Hoodie Snoopy",
        "stock": "60",
        "img": "https://http2.mlstatic.com/D_NQ_NP_939886-MLA50930008925_072022-O.webp",
        "price": "4600",
        "description": "Buzo Canguro Hoodie Negro Snoopy Mangas - Unisex",
        "categories": "Buzo",
        "brand": "Hoodie",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Canguro Hoodie Hello Kitty",
        "stock": "35",
        "img": "https://http2.mlstatic.com/D_NQ_NP_697161-MLA52052868269_102022-O.webp",
        "price": "2200",
        "description": "Buzo Canguro Hoodie Negro Hello Kitty Mangas - Unisex",
        "categories": "Buzo",
        "brand": "Hoodie",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Canguro Alpina Entallado",
        "stock": "75",
        "img": "https://http2.mlstatic.com/D_NQ_NP_978604-MLA51735555501_092022-O.webp",
        "price": "5300",
        "description": "Buzo Alpina Cuello Redondo Unisex Frisa Frizado",
        "categories": "Buzo",
        "brand": "Polo",
        "size": ["S","M","L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Seattle 1994",
        "stock": "15",
        "img": "https://http2.mlstatic.com/D_NQ_NP_649366-MLA51138072305_082022-O.webp",
        "price": "3300",
        "description": "Buzo De Algodon Gris - Seattle 1994 - Usa Aesthetic",
        "categories": "Buzo",
        "brand": "afa",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Canguro Blackpink",
        "stock": "45",
        "img": "https://http2.mlstatic.com/D_NQ_NP_623327-MLA47338019433_092021-O.webp",
        "price": "6300",
        "description": "Buzo Canguro Blackpink Grupo K-pop Banda Nene Nena Unisex",
        "categories": "Buzo",
        "brand": "Angles",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Canguro Interfuerzas",
        "stock": "32",
        "img": "https://http2.mlstatic.com/D_NQ_NP_901574-MLA50799938321_072022-O.webp",
        "price": "5000",
        "description": "Buzo Hombre Algodón Capucha Canguro Interfuerzas",
        "categories": "Buzo",
        "brand": "Friza",
        "size": ["S","M","L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Canguro Thrasher Orig",
        "stock": "75",
        "img": "https://http2.mlstatic.com/D_NQ_NP_720120-MLA47409003000_092021-O.webp",
        "price": "2300",
        "description": "Buzo Canguro Thrasher Orig Negro Let Blancas.",
        "categories": "Buzo",
        "brand": "Polo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },  
    {
        "name": "Maestro Roshi",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_957253-MLA50946156896_072022-O.webp",
        "price": "4000",
        "description": "Maestro Roshi - Buzo Canguro Unisex - Anime Dragon Ball 0",
        "categories": "Buzo",
        "brand": "Polo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Playstation Mod 2",
        "stock": "40",
        "img": "https://http2.mlstatic.com/D_NQ_NP_619304-MLA50941633950_072022-O.webp",
        "price": "4000",
        "description": "Playstation Mod 2 - Buzo Canguro Unisex - Gamer Playstation",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Playstation Mod 1",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_868060-MLA50941806032_072022-O.webp",
        "price": "1200",
        "description": "Playstation Mod 1 - Buzo Canguro Unisex - Gamer Playstation",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Spiderman",
        "stock": "10",
        "img": "https://http2.mlstatic.com/D_NQ_NP_842725-MLA50946424085_072022-O.webp",
        "price": "4300",
        "description": "Spiderman - Buzo Canguro Unisex - Spiderman Marvel",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Zelda Mod 2",
        "stock": "10",
        "img": "https://http2.mlstatic.com/D_NQ_NP_989721-MLA50946472874_072022-O.webp",
        "price": "4600",
        "description": "Zelda Mod 2 - Buzo Canguro Unisex - Nintendo",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Zelda Mod 1",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_774281-MLA50946490505_072022-O.webp",
        "price": "3000",
        "description": "Zelda Mod 1 - Buzo Canguro Unisex - Nintendo",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo The Punisher",
        "stock": "18",
        "img": "https://http2.mlstatic.com/D_NQ_NP_935239-MLA50946447481_072022-O.webp",
        "price": "4300",
        "description": "The Punisher - Buzo Canguro Unisex - Marvel",
        "categories": "Buzo",
        "brand": "mlstatic",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Marvel Logo",
        "stock": "13",
        "img": "https://http2.mlstatic.com/D_NQ_NP_957977-MLA50941625298_072022-O.webp",
        "price": "4600",
        "description": "Marvel Logo - Buzo Canguro Unisex - Marvel",
        "categories": "Buzo",
        "brand": "Armour",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Lil Peep",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_984476-MLA49163913679_022022-O.webp",
        "price": "5000",
        "description": "Lil Peep - Buzo Canguro Unisex - Angry Girl - Hip Hop",
        "categories": "Buzo",
        "brand": "Armour",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },  
    {
        "name": "Buzo Honda",
        "stock": "80",
        "img": "https://http2.mlstatic.com/D_NQ_NP_910620-MLA31124840981_062019-O.webp",
        "price": "4600",
        "description": "Honda - Buzo Canguro Con Capucha Algodón - Moto - Bike Cross",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Ktm Racing",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_884620-MLA31034876476_062019-O.webp",
        "price": "5500",
        "description": "Ktm Racing - Buzo Canguro Con Capucha - Motocross - Bike",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo John Deere",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_772057-MLA31020619954_062019-O.webp",
        "price": "5000",
        "description": "John Deere - Buzo Canguro Con Capucha Unisex - Vintage",
        "categories": "Buzo",
        "brand": "Geek",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Thrasher",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_902165-MLA51973970622_102022-O.webp",
        "price": "4300",
        "description": "Thrasher - Buzo Canguro Con Capucha - Mangas Con Flamas",
        "categories": "Buzo",
        "brand": "Keisuke",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Astroworld",
        "stock": "60",
        "img": "https://http2.mlstatic.com/D_NQ_NP_876023-MLA53177364466_012023-O.webp",
        "price": "4600",
        "description": "Astroworld Canguro Unisex Travis Scot - Wish You Were Here",
        "categories": "Buzo",
        "brand": "Trench",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Louis Tomlinson Walls",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_607589-MLA52605115172_112022-O.webp",
        "price": "5500",
        "description": "Louis Tomlinson Walls - Buzo Canguro Unisex - One Direction",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    {
        "name": "Buzo Drew Bieber Pop",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_614417-MLA52604967999_112022-O.webp",
        "price": "8000",
        "description": "Buzo Canguro Unisex Drew Bieber Pop Aesthetic Hype Street",
        "categories": "Buzo",
        "brand": "Rubius",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Dream Merch Smp",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_604707-MLA52951522939_122022-O.webp",
        "price": "4300",
        "description": "Dream Merch Smp - Buzo Canguro Unisex - Cosplay Smile",
        "categories": "Buzo",
        "brand": "Hoodie",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Karl Jacobs",
        "stock": "60",
        "img": "https://http2.mlstatic.com/D_NQ_NP_979148-MLA52950254175_122022-O.webp",
        "price": "4600",
        "description": "Karl Jacobs - Buzo Canguro Unisex - Youtuber Internet Viral",
        "categories": "Buzo",
        "brand": "Trench",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Mr Beast",
        "stock": "20",
        "img": "https://http2.mlstatic.com/D_NQ_NP_972503-MLA52398340581_112022-O.webp",
        "price": "5800",
        "description": "Mr Beast - Buzo Canguro Unisex - Youtuber Internet Viral",
        "categories": "Buzo",
        "brand": "Tokyo",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Renault Formula 1",
        "stock": "30",
        "img": "https://http2.mlstatic.com/D_NQ_NP_900130-MLA51480702028_092022-O.webp",
        "price": "4300",
        "description": "Buzo Renault Formula 1 Urbano -calidad Premium",
        "categories": "Buzo",
        "brand": "Jujutsu",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Buzo Red Bull F1",
        "stock": "60",
        "img": "https://http2.mlstatic.com/D_NQ_NP_605216-MLA50680137967_072022-O.webp",
        "price": "4600",
        "description": "Buzo Red Bull F1 2022 Urbano - Calidad Premium",
        "categories": "Buzo",
        "brand": "Hoodie",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    }, 
    {
        "name": "Buzo Mercedes F1",
        "stock": "35",
        "img": "https://http2.mlstatic.com/D_NQ_NP_720238-MLA50995928757_082022-O.webp",
        "price": "2200",
        "description": "Buzo Mercedes F1 2022 Urbano - Calidad Premium",
        "categories": "Buzo",
        "brand": "Hoodie",
        "size": ["S","M" , "L"],
        "colour": ["Azul","Negro","Blanco","Rojo"],
        "fabric": ["Algodón"],
    },
    // {
    //     "name": "Jordan",
    //     "stock": "12",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/655715-150-auto?v=638040447195600000&width=150&height=auto&aspect=true",
    //     "price": "44000",
    //     "description": "BOTITAS AIR JORDAN 1 MID",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["39","40","41","42","43","44","45"],
    //     "colour": ["Rojo", "Negro "],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "6",
    //     "imagen1":"https://essential.vtexassets.com/arquivos/ids/669179-150-auto?v=638064530776800000&width=150&height=auto&aspect=true",
    //     "price": "37500",
    //     "description": "BOTITAS JORDAN ZOOM SEPARATE",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["39","40","41","42","43","44"],
    //     "colour": ["Gris","Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "6",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/631888-150-auto?v=638006648529130000&width=150&height=auto&aspect=true",
    //     "price": "62500",
    //     "description": "BOTITAS JORDAN AIR 3 RETRO DARK IRIS",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["37","38","39","40","41","42","43","44","45","46","47"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "9",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/446380-150-auto?v=637612784162300000&width=150&height=auto&aspect=true",
    //     "price": "54500",
    //     "description": "BOTITAS JORDAN AIR 7 RETRO",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["39","40","41","42","43","44","45"],
    //     "colour": ["Blanco","Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "11",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/655715-800-auto?v=638040447195600000&width=800&height=auto&aspect=true",
    //     "price": "44000",
    //     "description": "BOTITAS AIR JORDAN 1 MID",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["39","40","41","42","43","44","45"],
    //     "colour": ["Rojo","Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "12",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/669920-150-auto?v=638066336173930000&width=150&height=auto&aspect=true",
    //     "price": "41000",
    //     "description": "BOTITAS JORDAN ZION 2",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["39","40","41","42","43","44","45"],
    //     "colour": ["Beige"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "7",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/641908-150-auto?v=638023112305130000&width=150&height=auto&aspect=true",    
    //     "price": "47500",
    //     "description": "BOTITAS JORDAN AIR JORDAN 6 RETRO",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["37","38","39","40","41"],
    //     "colour": ["Blanco","Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "14",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/641851-150-auto?v=638023112034570000&width=150&height=auto&aspect=true",
    //     "price": "27500",
    //     "description": "COURT LEGACY",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["34","35","36","37","38","39","40","41"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "11",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/641682-150-auto?v=638023111263070000&width=150&height=auto&aspect=true",
    //     "price": "26500",
    //     "description": "COURT LEGACY",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["34","35","36","37","38","39","40","41"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "9",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/573979-150-auto?v=637919758067200000&width=150&height=auto&aspect=true",
    //     "price": "34000",
    //     "description": "AIR HUARACHE",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["34","35","36","37","38","39","40","41"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "7",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/417521-150-auto?v=637538501165530000&width=150&height=auto&aspect=true",
    //     "price": "46500",
    //     "description": "AIR FORCE 1 GTX",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["35","36","37","38","39","40","41","42","43","44","45","46"],
    //     "colour": ["Marrón"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "14",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/388375-150-auto?v=637414808077630000&width=150&height=auto&aspect=true",
    //     "price": "33000",
    //     "description": "CORTEZ BASIC PREMIUM",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["34","35","36","37","38","39","40","41","42","43","44"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "4",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/655800-150-auto?v=638040469170330000&width=150&height=auto&aspect=true",
    //     "price": "42000",
    //     "description": "AIR FORCE 1 HIGHT 07 LV8",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["39","40","41","42","43","44"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "5",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/641726-150-auto?v=638023111466370000&width=150&height=auto&aspect=true",
    //     "price": "75500",
    //     "description": "AIR PRESTO MID",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["37","38","39","40","41","42","43","44","45","46"],
    //     "colour": ["Amarillo"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "10",
    //     "imagen1":"https://essential.vtexassets.com/arquivos/ids/655790-150-auto?v=638040469128170000&width=150&height=auto&aspect=true",
    //     "price": "47500",
    //     "description": "AIR MORE UPTEMPO '96",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["39","40","41","42","43","44","45"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "8",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/651922-150-auto?v=638035203528700000&width=150&height=auto&aspect=true",
    //     "price": "48500",
    //     "description": "AIR MORE UPTEMPO 96",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["39","40","41","42","43","44"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "16",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/636245-150-auto?v=638013860014570000&width=150&height=auto&aspect=true",
    //     "price": "38000",
    //     "description": "ORIGINALS FORUM",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "4",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/621946-150-auto?v=637988643316430000&width=150&height=auto&aspect=true",
    //     "price": "38500",
    //     "description": "ORIGINALS NMD_R1 V2",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "17",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/619248-150-auto?v=637983319435130000&width=150&height=auto&aspect=true",
    //     "price": "30500",
    //     "description": "ORIGINALS ZX 1K BOOST 2.0",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "7",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/621946-150-auto?v=637988643316430000&width=150&height=auto&aspect=true",
    //     "price": "38500",
    //     "description": "ORIGINALS NMD_R1 V2",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "9",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/606921-150-auto?v=637963393766070000&width=150&height=auto&aspect=true",
    //     "price": "38500",
    //     "description": "NMD_R1",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["39","40","41","42","43","44","45","46","47","48","49"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "11",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/544002-150-auto?v=637850383543770000&width=150&height=auto&aspect=true",
    //     "price": "37500",
    //     "description": "ORIGINALS SUPERSTAR",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["36","37","38","39","40","41","42"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "16",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/482746-150-auto?v=637703277492930000&width=150&height=auto&aspect=true",
    //     "price": "30000",
    //     "description": "ORIGINALS ZX 1K BOOST",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "8",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/240354-150-auto?v=636937132486730000&width=150&height=auto&aspect=true",
    //     "price": "24200",
    //     "description": "RIGINALS 3MC VULCANIZADOS",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["35","36","37","38","39","40","41","42","43","44"],
    //     "colour": ["Azul"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "15",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/435382-150-auto?v=637582266896100000&width=150&height=auto&aspect=true",
    //     "price": "35500",
    //     "description": "ORIGINALS FORUM LOW",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["34","35","36","37","38","39","40","41","42","43","44","45"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Adidas",
    //     "stock": "4",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/574084-150-auto?v=637919758566930000&width=150&height=auto&aspect=true",
    //     "price": "30500",
    //     "description": "ORIGINALS MULTIX",
    //     "categories": "Zapatillas",
    //     "brand": "Adidas",
    //     "size": ["37","38","39","40","41","42","43","44"],
    //     "colour": ["Rojo"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "New Balance",
    //     "stock": "6",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/654976-150-auto?v=638038960619700000&width=150&height=auto&aspect=true",
    //     "price": "35000",
    //     "description": "306 NCI",
    //     "categories": "Zapatillas",
    //     "brand": "New Balance",
    //     "size": ["39","40","41","42","43"],
    //     "colour": ["Azul"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "New Balance",
    //     "stock": "8",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/661604-150-auto?v=638048855425400000&width=150&height=auto&aspect=true",
    //     "price": "28500",
    //     "description": "DYNASOFT",
    //     "categories": "Zapatillas",
    //     "brand": "New Balance",
    //     "size": ["35","36","37","38","39"],
    //     "colour": ["Verde"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Fila",
    //     "stock": "7",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/525076-150-auto?v=637810513850570000&width=150&height=auto&aspect=true",
    //     "price": "31200",
    //     "description": "RAY TRACER",
    //     "categories": "Zapatillas",
    //     "brand": "Fila",
    //     "size": ["40","41","42","43","44","45"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Fila", 
    //     "stock": "5",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/542407-150-auto?v=637847790085530000&width=150&height=auto&aspect=true",
    //     "price": "43500",
    //     "description": "FLOAT RENNO",
    //     "categories": "Zapatillas",
    //     "brand": "Fila",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Fila",
    //     "stock": "4",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/649623-150-auto?v=638031814727600000&width=150&height=auto&aspect=true",
    //     "price": "46600",
    //     "description": "RENNO",
    //     "categories": "Zapatillas",
    //     "brand": "Fila",
    //     "size": ["35","36","37","38","39","40"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Fila",
    //     "stock": "12",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/626288-150-auto?v=637995506744330000&width=150&height=auto&aspect=true",
    //     "price": "46600",
    //     "description": "EXCURSION",
    //     "categories": "Zapatillas",
    //     "brand": "Fila",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Fila",
    //     "stock": "8",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/393364-150-auto?v=637425268904730000&width=150&height=auto&aspect=true",
    //     "price": "45900",
    //     "description": "ELECTROVE",
    //     "categories": "Zapatillas",
    //     "brand": "Fila",
    //     "size": ["35","36","37","38","39","40"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Puma",
    //     "stock": "10",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/669122-150-auto?v=638064444984070000&width=150&height=auto&aspect=true",
    //     "price": "42500",
    //     "description": "TRC BLAZE SPXP",
    //     "categories": "Zapatillas",
    //     "brand": "Puma",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Naranja, Azul"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Puma",
    //     "stock": "6",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/636201-800-auto?v=638013859810630000&width=800&height=auto&aspect=true",
    //     "price": "39000",
    //     "description": "TRC BLAZE",
    //     "categories": "Zapatillas",
    //     "brand": "Puma",
    //     "calification": "0",
    //     "size": ["40","41","42","43","44","45"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Puma",
    //     "stock": "4",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/645024-150-auto?v=638024806211030000&width=150&height=auto&aspect=true",
    //     "price": "39000",
    //     "description": "RS SIMUL8 SOFT",
    //     "categories": "Zapatillas",
    //     "brand": "Puma",
    //     "size": ["35","36","37","38","39","40"],
    //     "colour": ["Blanco"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "New Balance",
    //     "stock": "",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/649958-150-auto?v=638035146799330000&width=150&height=auto&aspect=true",
    //     "price": "36200",
    //     "description": "574",
    //     "categories": "Zapatillas",
    //     "brand": "New Balance",
    //     "size": ["38","39","40","41","42","43","44","45"],
    //     "colour": ["Negro","Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "New Balance",
    //     "stock": "8",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/641107-150-auto?v=638022541955730000&width=150&height=auto&aspect=true",
    //     "price": "37500",
    //     "description": "997",
    //     "categories": "Zapatillas",
    //     "brand": "New Balance",
    //     "size": ["39","40","41","42","43","44","45","46","47"],
    //     "colour": ["Blanco","Azul"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "New Balance",
    //     "stock": "6",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/638439-150-auto?v=638017337981070000&width=150&height=auto&aspect=true",
    //     "price": "33500",
    //     "description": "574",
    //     "categories": "Zapatillas",
    //     "brand": "New Balance",
    //     "size": ["39","40","41","42","43","44","45","46","47"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "8",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/576988-150-auto?v=637921838777700000&width=150&height=auto&aspect=true",
    //     "price": "41200",
    //     "description": "AIR MAX 90 SE",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["40","41","42","43","44"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "9",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/432205-150-auto?v=637571120506070000&width=150&height=auto&aspect=true",
    //     "price": "37500",
    //     "description": "AIR FORCE 1 07",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["35","36","37","38","39","40","41","42","43","44","45"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "12",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/165152-150-auto?v=636664753420630000&width=150&height=auto&aspect=true",
    //     "price": "27000",
    //     "description": "AIR FORCE 1",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["35","36","37","38"],
    //     "colour": ["Negro"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "3",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/460836-150-auto?v=637650557497430000&width=150&height=auto&aspect=true",
    //     "price": "37500",
    //     "description": "AF1 CRATER FLYKNIT",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["35","36","37","38","39","40","41"],
    //     "colour": ["Rosado"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Nike",
    //     "stock": "6",
    //     "img1":"https://essential.vtexassets.com/arquivos/ids/641645-150-auto?v=638023111087530000&width=150&height=auto&aspect=true",
    //     "price": "42500",
    //     "description": "PRESTO",
    //     "categories": "Zapatillas",
    //     "brand": "Nike",
    //     "size": ["35","36","37","38","39","40","41"],
    //     "colour": ["Gris"],
    //     "fabric": ["Algodón"],
    // },
    // {
    //     "name": "Jordan",
    //     "stock": "9",
    //     "img1": "https://essential.vtexassets.com/arquivos/ids/658713-150-auto?v=638043086098200000&width=150&height=auto&aspect=true",
    //     "price": "30000",
    //     "description": "BOTITAS ZION 2",
    //     "categories": "Zapatillas",
    //     "brand": "Jordan",
    //     "size": ["39","40","41","42","43","44","45","46"],
    //     "colour": ["Negro","Gris"],
    //     "fabric": ["Algodón"],
    // },
]

module.exports = jsonProducts;